version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aishwarya-portfolio
    restart: unless-stopped
    env_file:
      - .env.local # <-- Add this line
    ports:
      - "8100:3000"
